language: ruby
rvm:
  - 2.2.7
  - 2.3.4
  - 2.4.1
gemfile:
  - gemfiles/rails_4.1.gemfile
  - gemfiles/rails_4.2.gemfile
  - gemfiles/rails_5.0.gemfile
  - gemfiles/rails_5.1.gemfile
matrix:
  exclude:
    - rvm: 2.4.1
      gemfile: gemfiles/rails_4.1.gemfile
script:
  - bundle exec rspec spec
before_script:
  - cp spec/dummy/config/database.yml.ci spec/dummy/config/database.yml
  - RAILS_ENV=test bundle exec rake app:db:create app:db:migrate
after_script:
  - bundle exec codeclimate-test-reporter
env:
  global:
    - DEVISE_SECRET_KEY=foo
addons:
  code_climate:
    repo_token:
      secure: "e2vpIAPiaVnWD1w0JcWV2gl1LyNPqlUomlUeBvyHCEzxDpMxoXOTfsLQhQ/LzQC1FH9Ph0lXPRHfM7wL/WJxHThqHFpCM784lbE/Zbp9W9u8btMhCEl8ZYSynm/5+Ycsh8tJD7UCduCqdNF3zXJ450BwoVBcQri4FqsyWXp5lcE="
